version: "3"
services:    
    server:
        container_name: server
        build:
            context: ./server
                # volumes
        depends_on:
            - mongo
        volumes:
            - ".:/home/app/server"
        # command: >
        #     bash
        stdin_open: true # docker run -i
        tty: true # docker run -t
        ports : 
            - 8080:8080

    mongo:
        image: mongo
        container_name: mongo
        environment:
            # These are needed on database creation
            MONGO_INITDB_ROOT_USERNAME: restheart
            MONGO_INITDB_ROOT_PASSWORD: R3ste4rt!
        command: --bind_ip_all --auth
        volumes:
            - mongo-data:/data/db
        ports:
            - "27017:27017"

    mongo-express:
        image: mongo-express
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: example
            ME_CONFIG_MONGODB_URL: mongodb://restheart:R3ste4rt!@mongo:27017/

volumes:
  mongo-data: